FROM centos:7

RUN yum -y install epel-release && yum -y install libSM && yum -y install libXrender && yum -y install libXext && yum -y install gcc && yum -y install python36 && yum -y install python36-devel && yum -y install python36-pip && pip3 install pyfocus && yum clean all
